### ISSUE TITLE
Parse text error.

### ISSUE THREAD

**Issue by wenzhixin** [borgar/textile-js#18] opened 2014-07-30 02:59 UTC
Hi, when the text is:
```
h3. test
* 1
* 2
* 3
```
textile parse result is error:
```
<h3>test<br />
* 1<br />
* 2<br />
* 3</h3>
```
the correct result is:
```
<h3>test</h3>
<ul>
	<li>1</li>
	<li>2</li>
	<li>3</li>
</ul>
```
https://github.com/alexyoung/stextile parse that correct.

**Comment by borgar** [comment] 2015-01-12 11:45
RedCloth dingus is working again and I'm adding it's output here to document it in case this comes up again:

    <h3>test</h3>
    <ul>
        <li>1</li>
        <li>2</li>
        <li>3</li>
    </ul>

I still think this is a substandard output for reasons stated above and so I'm not reopening. Feel free to argue with me if you think you have a better line of reasoning.

**Comment by ang-st** [comment] 2015-04-10 15:02
Hello,
"\r" break the rendering of both numbered and bulleted list.

ie 
```
*1\n
*2\n
*3\n
```
render to 
```
<ul>
    <li>1</li>
    <li>2</li>
    <li>3</li>
</ul>
```

whereas 
```
*1\r\n
*2\r\n
*3\r\n
```
render to

```
<p>*1</p><p>*2</p><p>*3</p>
```

I ended with 
```
textile(mystring.repace(/\r/g,'')) //strip \r
```
as a quick fix

**Comment by borgar** [comment] 2015-04-14 19:17
I've converted the line breaking issue to a new ticket: #23

**Comment by borgar** [comment] 2016-01-14 11:40
This is a duplicate of #30, but as I am fixing that I might as well close this one in sync to document what happened, and so people get notified if they are watching.

**Closed** 2016-01-14 11:41 UTC
Labels: bug

**Comment by wenzhixin** [comment] 2016-01-15 14:32
Great, thanks!
